name: 'Terraform Infrastructure Workflow'

on:
  push:
    branches: [ "main", "aws-terraform-infra" ]
  pull_request:
    branches: [ "main", "aws-terraform-infra" ]
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform Action'
        required: true
        type: choice
        options:
          - apply
          - destroy

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: terraform/environments/prod

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::772102554033:role/github-terraform-role
          aws-region: ca-central-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.0"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: |
          if [ "${{ inputs.action }}" == "destroy" ]; then
            terraform plan -destroy
          else
            terraform plan
          fi

      - name: Terraform Apply
        if: inputs.action == 'apply' && github.event_name == 'workflow_dispatch'
        run: terraform apply -auto-approve

      - name: Terraform Destroy
        if: inputs.action == 'destroy' && github.event_name == 'workflow_dispatch'
        run: terraform destroy -auto-approve