# This is a basic workflow to help you get started with Actions
name: CI-terraform-Pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  push:
    branches: [ "main", "aws-terraform-infrastructure" ]
  pull_request:
    branches: [ "main", "aws-terraform-infrastructure" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Add these permissions - they're required for OIDC
permissions:
  id-token: write
  contents: read

# A workflow run is made up of one or more jobs
jobs:
  terraform:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: terraform/environments/staging

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::772102554033:role/github-terraform-role
          aws-region: ca-central-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.0"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        if: github.event_name == 'workflow_dispatch'
        run: terraform apply -auto-approve