name: 'Terraform Infrastructure Workflow'

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform Action'
        required: true
        type: choice
        options:
          - apply
          - destroy

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: terraform/environments/prod

    steps:
      - uses: actions/checkout@v4

      - name: Debug List Root Directory
        run: |
          echo "Current working directory: $GITHUB_WORKSPACE"
          ls -R

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::772102554033:role/github-terraform-role
          aws-region: ca-central-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.0"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: |
          if [ "${{ inputs.action }}" == "destroy" ]; then
            echo "Running Terraform Plan for Destroy..."
            terraform plan -destroy -out=tfplan
          else
            echo "Running Terraform Plan for Apply..."
            terraform plan -out=tfplan
          fi

      - name: Terraform Apply or Destroy
        run: |
          if [ "${{ inputs.action }}" == "destroy" ]; then
            echo "Executing Terraform Destroy..."
            terraform destroy -auto-approve
          else
            echo "Executing Terraform Apply..."
            terraform apply -auto-approve tfplan
          fi
