name: 'Terraform Deploy'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'prod'
        type: choice
        options:
          - prod

permissions:
  contents: read
  id-token: write
  actions: write
  pull-requests: write

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    environment: production
    
    defaults:
      run:
        working-directory: environments/prod

    steps:
    - uses: actions/checkout@v3
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::772102554033:role/github-terraform-role
        aws-region: ca-central-1

    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: "1.5.0"

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -var-file=terraform.tfvars

    - name: Terraform Apply
      run: terraform apply -var-file=terraform.tfvars -auto-approve