# This is a basic workflow to help you get started with Actions
name: 'Terraform Workflow'

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform Action (apply/destroy/import)'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy
          - import
      resource_address:
        description: 'Resource Address (for import)'
        required: false
        type: string
      resource_id:
        description: 'Resource ID (for import)'
        required: false
        type: string

permissions:
  id-token: write
  contents: read

# A workflow run is made up of one or more jobs
jobs:
  terraform:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: terraform/environments/prod

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::772102554033:role/github-terraform-role
          aws-region: ca-central-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.0"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Import
        if: inputs.action == 'import'
        run: |
          if [ -n "${{ inputs.resource_address }}" ] && [ -n "${{ inputs.resource_id }}" ]; then
            terraform import ${{ inputs.resource_address }} ${{ inputs.resource_id }}
          else
            echo "Resource address and ID are required for import"
            exit 1
          fi

      - name: Terraform Plan
        if: inputs.action == 'apply'
        id: plan
        run: terraform plan
        continue-on-error: true

      - name: Terraform Plan Destroy
        if: inputs.action == 'destroy'
        id: plan-destroy
        run: terraform plan -destroy
        continue-on-error: true

      - name: Terraform Apply
        if: inputs.action == 'apply' && github.event_name == 'workflow_dispatch'
        run: terraform apply

      - name: Terraform Destroy
        if: inputs.action == 'destroy' && github.event_name == 'workflow_dispatch'
        run: terraform destroy