name: 'Terraform Infrastructure Workflow'

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform Action'
        required: true
        type: choice
        options:
          - apply
          - destroy
          - inventory

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: terraform/environments/prod

    steps:
      - uses: actions/checkout@v4

      - name: Debug List Root Directory
        run: |
          echo "Current working directory: $GITHUB_WORKSPACE"
          ls -R

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::772102554033:role/github-terraform-role
          aws-region: ca-central-1

      - name: Setup Terraform
        if: inputs.action == 'apply' || inputs.action == 'destroy'
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.0"

      - name: Terraform Init
        if: inputs.action == 'apply' || inputs.action == 'destroy'
        run: terraform init

      - name: Terraform Plan
        if: inputs.action == 'apply' || inputs.action == 'destroy'
        run: |
          if [ "${{ inputs.action }}" == "destroy" ]; then
            echo "Running Terraform Plan for Destroy..."
            terraform plan -destroy -out=tfplan
          else
            echo "Running Terraform Plan for Apply..."
            terraform plan -out=tfplan
          fi

      - name: Terraform Apply or Destroy
        if: inputs.action == 'apply' || inputs.action == 'destroy'
        run: |
          if [ "${{ inputs.action }}" == "destroy" ]; then
            echo "Executing Terraform Destroy..."
            terraform destroy -auto-approve
          else
            echo "Executing Terraform Apply..."
            terraform apply -auto-approve tfplan
          fi

      - name: Setup Python
        if: inputs.action == 'inventory'
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        if: inputs.action == 'inventory'
        working-directory: .
        run: |
          python -m pip install --upgrade pip
          pip install boto3 botocore

      - name: Run Resource Inventory
        if: inputs.action == 'inventory'
        working-directory: .
        run: |
          python scripts/resources.py

      - name: Upload Inventory Report
        if: inputs.action == 'inventory'
        uses: actions/upload-artifact@v3
        with:
          name: aws-resource-inventory
          path: aws_resources_*.json
          retention-days: 30
